# Generated by Django 3.1.6 on 2021-11-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="author",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="done",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="solution",
        ),
        migrations.CreateModel(
            name="HomeworkResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution", models.TextField(blank=True, default="homework solution")),
                ("done", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
                (
                    "homework_src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.homework"
                    ),
                ),
            ],
        ),
    ]
